### PR TITLE
Workaround for JRuby

### PR DESCRIPTION
**Pull request by unitymind**
Little fix for JRuby compatibility.

### CODE REVIEW

**Comment by baschtl** [comment]
@unitymind Could you try to explain the issue? Otherwise I will close this PR as there has been no answer for some time now.

**Comment by unitymind** [comment]
At the moment of this fix JRuby implementation just fall back to  NoMethodError on try(:devise_mailer) instead nil.

**Comment by baschtl** [comment]
@unitymind Ok, thanks for the clarification. Is this not the case for current JRuby implementations anymore? To phrase it differently: is this still needed?

**Comment by unitymind** [comment]
I don't know, because reject Ruby in my work... It's bounded case for rare JRuby + defined custom mailer combination.

**Comment by baschtl** [comment]
@unitymind Ok. As nobody else seems to have this issue, are you Ok with closing it?

**Comment by unitymind** [comment]
Reject and close :)

**Pull request closed without merging**
