### PR TITLE
use deliver_now if possible in preparation for Rails 5

### PR DESCRIPTION
**Pull request by barelyknown**
This fixed https://github.com/mhfs/devise-async/issues/59.

### CODE REVIEW

**Comment by emq** [comment]
Side note: as rails 4.2 ships with activejob you can simply [do this][1] to achieve what devise-async is doing. Sooo... this kinda makes this gem obsolete (more or less, depending on your needs obviously).

[1]: https://github.com/plataformatec/devise#activejob-integration

**Comment by marcgg** [comment]
This seems interesting, is it going to be merged ?

**Comment by futhr** [comment]
@marcgg as @emq and Devise information is pointing out its a tiny 3 line method (+ tests) that's kind of superseeds this gem. And it works very well.

**Comment by baschtl** [comment]
@barelyknown I guess this is still somewhat useful. Could you fix the merge conflicts? Then we would be able to merge it.

**Comment by baschtl** [comment]
@barelyknown Thanks!

**Pull request merged**
